# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2016)),
                ('pub_date', models.DateTimeField(verbose_name='published')),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('cover', models.FileField(upload_to='img/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(choices=[('I', 'ACT I'), ('II', 'ACT II'), ('III', 'ACT III')], default='I', max_length=2)),
                ('sequence', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=140)),
                ('image', models.FileField(upload_to='img/')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='movies.Movie')),
            ],
        ),
    ]
