# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 2, 4, 18, 31, 23, 207077, tzinfo=utc), max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
