# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='begin',
            field=models.CharField(default='00:00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='end',
            field=models.CharField(default='00:00', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.FileField(upload_to='img/sequences/'),
        ),
    ]
