# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160208_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.FileField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.FileField(upload_to='sequences/'),
        ),
        migrations.AlterField(
            model_name='script',
            name='sequence',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1),
        ),
    ]
