# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160204_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
