# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20160205_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(default=datetime.datetime(2016, 2, 5, 13, 16, 4, 141769, tzinfo=utc), upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='act',
            field=models.CharField(choices=[('I', 'ACT I'), ('II', 'ACT II'), ('III', 'ACT III')], default='I', max_length=2),
        ),
    ]
